### ISSUE TITLE
!msgalert Command

### ISSUE THREAD

**Issue by UnacceptableUse** [UnacceptableUse/UnacceptableBOT2#42]
Pings/PMs user when a new message is posted

**Comment by eduardog3000** [comment]
When a new message is posted where?

**Comment by UnacceptableUse** [comment]
In whatever channel the command I'd executed in

**Comment by eduardog3000** [comment]
So like, I run "!msgalert #channel", and the bot will PM me *every* time someone says something in that channel?

**Comment by UnacceptableUse** [comment]
Only the first time, unless you can add some sort of stop command

**Comment by eduardog3000** [comment]
lol, oops
