### ISSUE TITLE
Fix for 100 message topic changing

### ISSUE THREAD

**Issue by teknogeek** [UnacceptableUse/UnacceptableBOT2#43]
Commit b1d05dcd4ada54a9f82fe434338149d3f3252324 broke how the topic changed every 100 messages in ##Ocelotworks. 

This happens because it no longer checks if the message is coming from ##Ocelotworks when incrementing the message count. Therefore, the topic is changed every 100 messages total for all channels the bot is in. 

To fix this, change:
```java
private static void doTopicTick(String channel)
{
	messageCount++;
	if(messageCount > 100)
	{
		updateTopic();
		currentTopic++;
		messageCount = 0;
	}
}
```
to
```java
private static void doTopicTick(String channel)
{
	if(channel.equals("##Ocelotworks"))
	{
		messageCount++;
		if(messageCount > 100)
		{
			updateTopic();
			currentTopic++;
			messageCount = 0;
		}
	}
}
```
[Lines 214-223](https://github.com/UnacceptableUse/UnacceptableBOT2/blob/master/src/com/unacceptableuse/unacceptablebot/UnacceptableBot.java#L214-L223)

**Comment by dvd604** [comment]
Patching up now
